# DO NOT EDIT THIS FILE
# file tangled from config.org

if status is-interactive
    keychain --eval --quiet --quick --nogui $SSH_KEYS_TO_AUTOLOAD | source # ssh
end

if test (tty) = /dev/tty1
    sway
end

set -g direnv_fish_mode eval_on_arrow # sourced direnv hook

set -x MANPAGER "sh -c 'col -bx | bat -l man -p'"
set -x DOOMDIR "~/.config/doom"
set -x EDITOR nvim

source ~/.config/nnn/init # nnn
source ~/.config/cheat/init # cheat
source ~/.config/starship/init # starship
source /opt/asdf-vm/asdf.fish # asdf
source ~/.config/zoxide/init # zoxide

alias cd z
