default-remote: local
remotes:
  images:
    addr: https://images.linuxcontainers.org
    protocol: simplestreams
    public: true
  local:
    addr: unix://
    public: false
aliases:
  login: exec @ARGS@ --mode interactive -- bash -xc {exec,login,-p,-f,$USER}
