[colors.bright]
black = "0x928374"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xdfbf8e"
yellow = "0xe3a84e"

[colors.normal]
black = "0x665c54"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xdfbf8e"
yellow = "0xe78a4e"

[colors.primary]
background = "0x282828"
foreground = "0xdfbf8e"

[font]
size = 11.0

[font.bold]
family = "JetBrains Mono NF"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono NF"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono NF"
style = "Italic"

[font.normal]
family = "JetBrains Mono NF"
style = "Regular"

# [schemes.gruvbox_material_dark.bright]
# black = "0x928374"
# blue = "0x7daea3"
# cyan = "0x89b482"
# green = "0xa9b665"
# magenta = "0xd3869b"
# red = "0xea6962"
# white = "0xdfbf8e"
# yellow = "0xe3a84e"
#
# [schemes.gruvbox_material_dark.normal]
# black = "0x665c54"
# blue = "0x7daea3"
# cyan = "0x89b482"
# green = "0xa9b665"
# magenta = "0xd3869b"
# red = "0xea6962"
# white = "0xdfbf8e"
# yellow = "0xe78a4e"
#
# [schemes.gruvbox_material_dark.primary]
# background = "0x282828"
# foreground = "0xdfbf8e"
#
# [schemes.gruvbox_material_light.bright]
# black = "0x654735"
# blue = "0x45707a"
# cyan = "0x4c7a5d"
# green = "0x6c782e"
# magenta = "0x945e80"
# red = "0xc14a4a"
# white = "0xf2e5bc"
# yellow = "0xb47109"
#
# [schemes.gruvbox_material_light.normal]
# black = "0x654735"
# blue = "0x45707a"
# cyan = "0x4c7a5d"
# green = "0x6c782e"
# magenta = "0x945e80"
# red = "0xc14a4a"
# white = "0xf2e5bc"
# yellow = "0xb47109"
#
# [schemes.gruvbox_material_light.primary]
# background = "0xf9f5d7"
# foreground = "0x654735"

[selection]
save_to_clipboard = true

[window.padding]
x = 3
y = 0
