# logging happens at:
# ~/.cache/starship/session_${STARSHIP_SESSION_KEY}.log

add_newline = true

# prompt
# see https://github.com/starship/starship/issues/4953
right_format = """$all"""
format = """$character"""

[character] 
success_symbol = "[λ](bold green)"
error_symbol = "[λ](bold red)"
